### ISSUE TITLE
Build on Manjaro20 error.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [adrg/libvlc-go#48] opened 2020-05-17 11:36 UTC
execute `go build`, then output below log:

```log
[zgx@sayed main]$ go build
# github.com/adrg/libvlc-go/v3
cgo-gcc-prolog: 在函数‘_cgo_c7c856de85d4_Cfunc_libvlc_media_is_parsed’中:
cgo-gcc-prolog:173:2: 警告：‘libvlc_media_is_parsed’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/vlc/vlc.h:51,
                 from ../../../pkg/mod/github.com/adrg/libvlc-go/v3@v3.0.3/media.go:4:
/usr/include/vlc/deprecated.h:249:4: 附注：在此声明
  249 |    libvlc_media_is_parsed( libvlc_media_t *p_md );
      |    ^~~~~~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: 在函数‘_cgo_c7c856de85d4_Cfunc_libvlc_media_parse’中:
cgo-gcc-prolog:226:2: 警告：‘libvlc_media_parse’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/vlc/vlc.h:51,
                 from ../../../pkg/mod/github.com/adrg/libvlc-go/v3@v3.0.3/media.go:4:
/usr/include/vlc/deprecated.h:209:1: 附注：在此声明
  209 | libvlc_media_parse( libvlc_media_t *p_md );
      | ^~~~~~~~~~~~~~~~~~
cgo-gcc-prolog: 在函数‘_cgo_c7c856de85d4_Cfunc_libvlc_media_parse_async’中:
cgo-gcc-prolog:238:2: 警告：‘libvlc_media_parse_async’ is deprecated [-Wdeprecated-declarations]
In file included from /usr/include/vlc/vlc.h:51,
                 from ../../../pkg/mod/github.com/adrg/libvlc-go/v3@v3.0.3/media.go:4:
/usr/include/vlc/deprecated.h:233:1: 附注：在此声明
  233 | libvlc_media_parse_async( libvlc_media_t *p_md );
      | ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by adrg** [comment] 2020-05-17 13:05
Hi @MiyamuraMiyako. Those are just some deprecation notices for some bindings which are still supported in libVLC v3. As long as your binary gets built, don't worry about those.
See https://github.com/adrg/libvlc-go/issues/40#issuecomment-623181968 for instructions on how to suppress those warnings.

Duplicate of #40.

**Closed** 2020-05-18 05:32 UTC
