### ISSUE TITLE
help! libvlc-go can not run

### ISSUE THREAD

**Issue by biij5698** [adrg/libvlc-go#11] opened 2017-11-17 10:35 UTC
when I run the useage code It report like this:
Module must be initialized first

**Comment by adrg** [comment] 2017-11-21 16:26
Hi there

Do you have this part in your code, at the beginning ?

    // Initialize libvlc. Additional command line arguments can be passed in
    // to libvlc by specifying them in the Init function.
    if err := vlc.Init("--no-video", "--quiet"); err != nil {
        log.Fatal(err)
    }
    defer vlc.Release()

If so, it means that VLC init fails without throwing an error. Do you have libvlc-dev installed on your
machine?

**Comment by T4cC0re** [comment] 2018-03-22 21:41
I can reproduce this on macOS High Sierra, but the same code works fine on Arch Linux. I am pretty sure it has something to do with paths of the vlccore subsystem. No idea why that is though. Yu might try adding "-vvv" to the init arguments to see further output.

**Comment by tenthree** [comment] 2018-09-13 09:33
Does it work on windows?

I follow the libvlc wiki guide to install sdk then "go run" output the same message on windows 10.

Thanks.

![snapshot2](https://user-images.githubusercontent.com/3132794/45480215-11a9c800-b77b-11e8-88e0-ec8eef4ef41a.png)

**Comment by adrg** [comment] 2018-09-13 10:51
@tenthree I don't use Windows at all so I don't know for sure. I see no reason for it not working on Windows though. Maybe someone in the community can confirm that it works. Do you have VLC player installed?

**Comment by tenthree** [comment] 2018-09-14 04:09
@adrg  Sorry for the late reply.
You are right!

Not only sdk directory but also the vlc player related execution directories and files  in "vlc-3.0.4-win64.7z" are requirement.

It's working after I put them all into mingw environment. (e.g. C:\mingw64\bin)

system: windows 10.
go version: go1.11 windows/amd64

steps:
1. install mingw on Windows
2. download 7z version(sdk included) from https://download.videolan.org/pub/videolan/vlc/3.0.4/win64
3. extract and get files below
![snapshot](https://user-images.githubusercontent.com/3132794/45529022-a8c35e00-b815-11e8-8647-3845183cca56.png)
4. put the blue line items in C:\mingw64\bin
5. put sdk/include in C:\mingw64\x86_64-w64-mingw32\include
6. put sdk/lib in C:\mingw64\x86_64-w64-mingw32\lib

It works for me, maybe helpful to someone.

Thanks.

**Comment by adrg** [comment] 2018-09-14 06:33
@tenthree Glad you were able to make it work. Also, thanks for the detailed steps. Hopefully, it will help other people as well.

**Comment by rishabh0417** [comment] 2019-05-30 19:01
I was also not able to run libvlc-go and getting the same error as mentioned above.
I am using Ubuntu 19.04 with libvlc-dev installed.
I am running the given sample code and yet get the "Module must be initialized first" 

Any suggestions on what to do next?

**Comment by sndnvaps** [comment] 2019-11-05 03:20
i have got the same problem..
system: windows 7 x64.
go version: go1.13.1 windows/386
libvlc version: vlc-3.0.8-win32.7z
my test example:
```go
package main

// #cgo CFLAGS: -IF:\Software_backup\libvlc-sdk-3.0.8-win32\vlc-3.0.8\sdk\include
// #cgo LDFLAGS: -LF:\Software_backup\libvlc-sdk-3.0.8-win32\vlc-3.0.8
// #cgo LDFLAGS: -lvlc
import (
	"fmt"
	"log"

	vlc "github.com/adrg/libvlc-go"
	"github.com/gohouse/e"
)

func main() {

	// Init for error output
	var err e.Error

	// Initialize libvlc. Additional command line arguments can be passed in
	// to libvlc by specifying them in the Init function.

	//error := vlc.Init("--no-video", "--quiet")
	error := vlc.Init()
	if error != nil {
		err = e.New(error.Error())
		fmt.Println("Error Line: ", err.GetLine())
		log.Fatal("Error msg: ", err.Error())
	}

	defer vlc.Release()
	// Create a new player.
	player, error := vlc.NewPlayer()
	if error != nil {
		err = e.New(error.Error())
		fmt.Println("Error Line: ", err.GetLine())
		log.Fatal("Error msg: ", err.Error())
	}
	defer func() {
		player.Stop()
		player.Release()
	}()

	// Add a media file from path or from URL.
	// Set player media from path:
	// media, err := player.LoadMediaFromPath("localpath/test.mp4")
	// Set player media from URL:
	media, error := player.LoadMediaFromURL("rtsp://192.168.13.100:8554/live1.mpeg")
	if error != nil {
		err = e.New(error.Error())
		fmt.Println("Error Line: ", err.GetLine())
		log.Fatal("Error msg: ", err.Error())
	}
	defer media.Release()

	// Start playing the media.
	error = player.Play()
	if error != nil {
		err = e.New(error.Error())
		fmt.Println("Error Line: ", err.GetLine())
		log.Fatal("Error msg: ", err.Error())
	}

	// Retrieve player event manager.
	manager, error := player.EventManager()
	if error != nil {
		err = e.New(error.Error())
		fmt.Println("Error Line: ", err.GetLine())
		log.Fatal("Error msg: ", err.Error())
	}

	// Register the media end reached event with the event manager.
	quit := make(chan struct{})
	eventCallback := func(event vlc.Event, userData interface{}) {
		close(quit)
	}

	eventID, error := manager.Attach(vlc.MediaPlayerEndReached, eventCallback, nil)
	if error != nil {
		err = e.New(error.Error())
		fmt.Println("Error Line: ", err.GetLine())
		log.Fatal("Error msg: ", err.Error())
	}
	defer manager.Detach(eventID)

	<-quit
}
```
error msg:
```bash
Error Line:  34
2019/11/05 10:58:27 Error Msg: module must be initialized first
```

**Comment by adrg** [comment] 2019-11-05 18:18
@rishabh0417 I have Ubuntu 18.04 and all I had to do is install libvlc-dev using apt-get so the files are placed in the standard locations. Did you do the same on Ubuntu 19.04? I will  test on the newer version of Ubuntu as well.
@sndnvaps I will test on Windows sometime this week and add detailed instructions on how to run the library.

**Comment by sndnvaps** [comment] 2019-11-06 03:28
@adrg thanks

**Comment by adrg** [comment] 2020-02-10 12:44
I added a wiki page with instructions on how to install libVLC on Windows: https://github.com/adrg/libvlc-go/wiki/Install-on-Windows.

**Comment by adrg** [comment] 2020-02-14 07:56
If you get `module must be initialized first` or `module not initialized` errors on Ubuntu or other Debian based distributions, also install the: `vlc-plugin-base` package. Installing the `vlc` package also works, but it install much more than the base plugins. So:

```bash
sudo apt-get install libvlc-dev
sudo apt-get install vlc-plugin-base
```

I also created a wiki page for installing the dependencies on Linux: https://github.com/adrg/libvlc-go/wiki/Install-on-Linux.

@rishabh0417 Does this solve the issue for you?

**Comment by adrg** [comment] 2020-03-11 14:15
Closing this issue due to age. Installation instructions for Windows and Linux have been provided. Please open another issue if the solutions in this one do not work for you.

**Closed by adrg** 2020-03-11 14:15 UTC
